version: "3.8"

services:
  pgdb:
    # profiles: [ "dev" ]
    container_name: pgdb_producthunt
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=producthunt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=producthunt

